class Content < ApplicationRecord
  def self.permitted_misc_functions
    ["to_s", "each", "each_with_index", "unshift", "length", "split", "new", "downcase", "upcase", "reverse", "gsub"]
  end

  def self.permitted_arr_functions
    ["to_h", "include?", "at", "fetch", "last", "push", "append", "pop", "shift", "unshift", "each_index", "join", "rotate", "rotate!", "sort!", "sort_by!", "collect!", "map!", "select!", "keep_if", "values_at", "delete_at", "delete_if", "reject!", "transpose", "+", "assoc", "rassoc", "fill", "-", "compact", "flatten", "flatten!", "shuffle!", "uniq!", "shuffle", "permutation", "combination", "*", "repeated_permutation", "&", "sample", "repeated_combination", "product", "bsearch", "compact!", "bsearch_index", "sort", "count", "find_index", "select", "reject", "collect", "map", "first", "any?", "reverse_each", "zip", "take", "take_while", "drop", "drop_while", "cycle", "sum", "uniq", "|", "insert", "pack", "<=>", "<<", "index", "rindex", "replace", "==", "clear", "[]", "[]=", "empty?", "eql?", "reverse", "reverse!", "concat", "inspect", "prepend", "max", "min", "length", "size", "each", "to_ary", "delete", "to_a", "to_s", "slice", "slice!", "dig", "hash", "frozen?", "lazy", "to_set", "find", "entries", "sort_by", "grep", "grep_v", "detect", "find_all", "flat_map", "collect_concat", "inject", "reduce", "partition", "group_by", "all?", "one?", "none?", "minmax", "min_by", "max_by", "minmax_by", "member?", "each_with_index", "each_entry", "each_slice", "each_cons", "each_with_object", "chunk", "slice_before", "slice_after", "slice_when", "chunk_while", "instance_variable_set", "instance_variable_defined?", "remove_instance_variable", "instance_of?", "kind_of?", "is_a?", "tap", "instance_variable_get", "public_methods", "instance_variables", "method", "public_method", "define_singleton_method", "public_send", "singleton_method", "extend", "pp", "to_enum", "enum_for", "gem", "===", "=~", "!~", "respond_to?", "freeze", "object_id", "send", "display", "nil?", "class", "singleton_class", "clone", "itself", "dup"]
  end

  def self.permitted_str_functions
    ["encode!", "include?", "%", "*", "+", "count", "partition", "to_c", "sum", "next", "casecmp", "casecmp?", "insert", "bytesize", "match", "match?", "succ!", "<=>", "next!", "index", "rindex", "upto", "==", "===", "chr", "=~", "byteslice", "[]", "[]=", "scrub!", "getbyte", "replace", "clear", "scrub", "empty?", "eql?", "-@", "downcase", "upcase", "dump", "setbyte", "swapcase", "+@", "capitalize", "capitalize!", "undump", "downcase!", "oct", "swapcase!", "lines", "bytes", "split", "codepoints", "freeze", "inspect", "reverse!", "grapheme_clusters", "reverse", "hex", "scan", "upcase!", "crypt", "ord", "chars", "prepend", "length", "size", "start_with?", "succ", "sub", "intern", "chop", "center", "<<", "concat", "strip", "lstrip", "end_with?", "delete_prefix", "to_str", "to_sym", "gsub!", "rstrip", "gsub", "delete_suffix", "to_s", "to_i", "rjust", "chomp!", "strip!", "lstrip!", "sub!", "chomp", "chop!", "ljust", "tr_s", "delete", "rstrip!", "delete_prefix!", "delete_suffix!", "tr", "squeeze!", "each_line", "to_f", "tr!", "tr_s!", "delete!", "slice", "slice!", "each_byte", "squeeze", "each_codepoint", "each_grapheme_cluster", "valid_encoding?", "ascii_only?", "rpartition", "encoding", "hash", "b", "unicode_normalize!", "unicode_normalized?", "to_r", "force_encoding", "each_char", "encode", "unicode_normalize", "unpack", "unpack1", "<=", ">=", "between?", "<", ">", "clamp", "instance_variable_set", "instance_variable_defined?", "remove_instance_variable", "instance_of?", "kind_of?", "is_a?", "tap", "instance_variable_get", "public_methods", "instance_variables", "method", "public_method", "define_singleton_method", "public_send", "singleton_method", "extend", "pp", "to_enum", "enum_for", "gem", "!~", "respond_to?", "object_id", "send", "display", "nil?", "class", "singleton_class", "clone", "itself", "dup"]
  end

  def self.permitted_object_functions
    ["index", "<=", "replace", "==", "clear", ">=", "[]", "to_h", "[]=", "include?", "fetch", "eql?", "empty?", "shift", "select!", "keep_if", "values_at", "delete_if", "inspect", "reject!", "assoc", "rassoc", "compact", "compact!", "flatten", "length", "size", "each", "<", ">", "rehash", "store", "default", "default=", "default_proc", "default_proc=", "to_hash", "to_proc", "each_value", "to_a", "to_s", "transform_keys", "transform_values!", "each_pair", "values", "keys", "transform_values", "fetch_values", "slice", "transform_keys!", "select", "each_key", "update", "reject", "merge", "invert", "has_value?", "delete", "value?", "has_key?", "compare_by_identity?", "key?", "merge!", "compare_by_identity", "any?", "dig", "member?", "hash", "key", "lazy", "to_set", "max", "min", "find", "entries", "sort", "sort_by", "grep", "grep_v", "count", "detect", "find_index", "find_all", "collect", "map", "flat_map", "collect_concat", "inject", "reduce", "partition", "group_by", "first", "all?", "one?", "none?", "minmax", "min_by", "max_by", "minmax_by", "each_with_index", "reverse_each", "each_entry", "each_slice", "each_cons", "each_with_object", "zip", "take", "take_while", "drop", "drop_while", "cycle", "chunk", "slice_before", "slice_after", "slice_when", "chunk_while", "sum", "uniq", "instance_variable_set", "instance_variable_defined?", "remove_instance_variable", "instance_of?", "kind_of?", "is_a?", "tap", "instance_variable_get", "public_methods", "instance_variables", "method", "public_method", "define_singleton_method", "public_send", "singleton_method", "extend", "pp", "to_enum", "enum_for", "gem", "<=>", "===", "=~", "!~", "respond_to?", "freeze", "object_id", "send", "display", "nil?", "class", "singleton_class", "clone", "itself", "dup"]
  end
end
